// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID        int64
	UserID    int64
	KeyHash   string
	KeyPrefix string
	CreatedAt sql.NullTime
	ExpiresAt sql.NullTime
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	IDToken   string
	CreatedAt sql.NullTime
	ExpiresAt time.Time
}

type User struct {
	ID        int64
	OidcSub   string
	Email     string
	Name      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
