// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"context"
	"database/sql"
	"time"
)

type User struct {
	ID        int64          `json:"id"`
	OIDCSub   string         `json:"oidc_sub"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type APIKey struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	KeyHash   string    `json:"key_hash"`
	KeyPrefix string    `json:"key_prefix"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

type Session struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (oidc_sub, email, name)
VALUES (?, ?, ?)
RETURNING id, oidc_sub, email, name, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, oidcSub string, email string, name sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, oidcSub, email, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OIDCSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOIDCSub = `-- name: GetUserByOIDCSub :one
SELECT id, oidc_sub, email, name, created_at, updated_at FROM users
WHERE oidc_sub = ?
LIMIT 1
`

func (q *Queries) GetUserByOIDCSub(ctx context.Context, oidcSub string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOIDCSub, oidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OIDCSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, oidc_sub, email, name, created_at, updated_at FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OIDCSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = ?, name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateUser(ctx context.Context, id int64, email string, name sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updateUser, email, name, id)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_hash, key_prefix)
VALUES (?, ?, ?)
RETURNING id, user_id, key_hash, key_prefix, created_at, expires_at
`

func (q *Queries) CreateAPIKey(ctx context.Context, userID int64, keyHash string, keyPrefix string) (APIKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey, userID, keyHash, keyPrefix)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, key_hash, key_prefix, created_at, expires_at FROM api_keys
WHERE key_hash = ?
LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (APIKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyByUserID = `-- name: GetAPIKeyByUserID :one
SELECT id, user_id, key_hash, key_prefix, created_at, expires_at FROM api_keys
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetAPIKeyByUserID(ctx context.Context, userID int64) (APIKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByUserID, userID)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys
WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, token, created_at, expires_at
`

func (q *Queries) CreateSession(ctx context.Context, userID int64, token string, expiresAt time.Time) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, userID, token, expiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, token, created_at, expires_at FROM sessions
WHERE token = ?
LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT id, user_id, token, created_at, expires_at FROM sessions
WHERE user_id = ?
AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) ListSessionsByUserID(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// Queries contains all the query methods
type Queries struct {
	db *sql.DB
}

// New creates a new Queries instance
func New(db *sql.DB) *Queries {
	return &Queries{db: db}
}
