name: Go build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25.x", "1.26.x"]

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build project
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
        run: >
          go build
          -o languagetool-user-proxy
          cmd/server/main.go

      - name: Check for static binary
        run: ldd languagetool-user-proxy 2>&1 | grep 'not a dynamic executable'

      - name: Run binary
        run: ./languagetool-user-proxy --help
